#!/bin/bash

# Lookout S3 Logger Quick Setup Script
# This script automates the setup process for the S3 logging service

set -e  # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Function to check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Function to prompt for user input
prompt_input() {
    local prompt="$1"
    local var_name="$2"
    local default="$3"
    
    if [ -n "$default" ]; then
        read -p "$prompt [$default]: " input
        if [ -z "$input" ]; then
            input="$default"
        fi
    else
        read -p "$prompt: " input
        while [ -z "$input" ]; do
            print_warning "This field is required."
            read -p "$prompt: " input
        done
    fi
    
    eval "$var_name='$input'"
}

# Main setup function
main() {
    echo "🚀 Lookout S3 Logger Quick Setup"
    echo "=================================="
    echo
    
    # Check prerequisites
    print_status "Checking prerequisites..."
    
    if ! command_exists python3; then
        print_error "Python 3 is required but not installed."
        exit 1
    fi
    
    if ! command_exists pip; then
        print_error "pip is required but not installed."
        exit 1
    fi
    
    if ! command_exists aws; then
        print_warning "AWS CLI not found. Installing AWS CLI is recommended for easier management."
    fi
    
    print_success "Prerequisites check completed"
    echo
    
    # Get configuration from user
    print_status "Gathering configuration..."
    echo
    
    prompt_input "Enter your Lookout API access token" LOOKOUT_TOKEN
    prompt_input "Enter S3 bucket name for logs" BUCKET_NAME
    prompt_input "Enter Kinesis Firehose stream name" STREAM_NAME
    prompt_input "Enter AWS region" AWS_REGION "us-east-1"
    
    echo
    print_status "Configuration summary:"
    echo "  Bucket Name: $BUCKET_NAME"
    echo "  Stream Name: $STREAM_NAME"
    echo "  AWS Region: $AWS_REGION"
    echo
    
    read -p "Continue with setup? (y/N): " confirm
    if [[ ! $confirm =~ ^[Yy]$ ]]; then
        print_warning "Setup cancelled by user"
        exit 0
    fi
    
    # Install Python dependencies
    print_status "Installing Python dependencies..."
    pip install -r requirements_s3.txt
    print_success "Dependencies installed"
    echo
    
    # Create environment file
    print_status "Creating environment configuration..."
    cat > .env << EOF
# Lookout S3 Logger Configuration
# Generated by setup script on $(date)

# Lookout API Configuration
LOOKOUT_ACCESS_TOKEN=$LOOKOUT_TOKEN
LOOKOUT_API_URL=https://mtp.lookout.com/data/web-access-feed

# AWS Configuration
AWS_REGION=$AWS_REGION
S3_BUCKET_NAME=$BUCKET_NAME
FIREHOSE_STREAM_NAME=$STREAM_NAME

# Service Configuration
POLL_INTERVAL=300
BUFFER_SIZE_LIMIT=500
BUFFER_TIME_LIMIT=300
LOG_LEVEL=INFO
MAX_RETRIES=3
RETRY_DELAY=60
EOF
    print_success "Environment file created (.env)"
    echo
    
    # Setup AWS infrastructure
    print_status "Setting up AWS infrastructure..."
    echo "This will create:"
    echo "  - S3 bucket with lifecycle policies"
    echo "  - Kinesis Data Firehose stream"
    echo "  - IAM roles and policies"
    echo "  - AWS Glue catalog for Athena"
    echo
    
    read -p "Proceed with AWS setup? (y/N): " aws_confirm
    if [[ $aws_confirm =~ ^[Yy]$ ]]; then
        python aws_setup.py \
            --bucket-name "$BUCKET_NAME" \
            --stream-name "$STREAM_NAME" \
            --region "$AWS_REGION"
        
        if [ $? -eq 0 ]; then
            print_success "AWS infrastructure setup completed"
        else
            print_error "AWS setup failed. Please check your AWS credentials and permissions."
            exit 1
        fi
    else
        print_warning "AWS setup skipped. You'll need to set up the infrastructure manually."
    fi
    echo
    
    # Run tests
    print_status "Running configuration tests..."
    python test_s3_logger.py
    
    if [ $? -eq 0 ]; then
        print_success "All tests passed!"
    else
        print_error "Some tests failed. Please check the configuration."
        exit 1
    fi
    echo
    
    # Deployment options
    print_status "Setup completed successfully! 🎉"
    echo
    echo "Next steps - Choose your deployment method:"
    echo
    echo "1. 🖥️  Run manually (for testing):"
    echo "   python lookout_s3_logger.py"
    echo
    echo "2. 🐳 Run with Docker:"
    echo "   cd docker && docker-compose up -d"
    echo
    echo "3. 🔧 Install as systemd service:"
    echo "   sudo cp systemd/lookout-s3-logger.service /etc/systemd/system/"
    echo "   sudo systemctl enable lookout-s3-logger"
    echo "   sudo systemctl start lookout-s3-logger"
    echo
    echo "4. 📊 Monitor the service:"
    echo "   - Check logs: journalctl -u lookout-s3-logger -f"
    echo "   - View CloudWatch metrics in AWS console"
    echo "   - Query data with Athena (database: lookout_security)"
    echo
    echo "📚 For detailed documentation, see README_S3_LOGGING.md"
    echo
    print_success "Setup complete! Your Lookout web activity data will now be streamed to S3."
}

# Check if running as root for systemd installation
check_systemd_install() {
    if [ "$1" = "--install-service" ]; then
        if [ "$EUID" -ne 0 ]; then
            print_error "Please run with sudo for systemd service installation"
            exit 1
        fi
        
        print_status "Installing systemd service..."
        cp systemd/lookout-s3-logger.service /etc/systemd/system/
        systemctl daemon-reload
        systemctl enable lookout-s3-logger
        systemctl start lookout-s3-logger
        print_success "Systemd service installed and started"
        
        echo
        echo "Service management commands:"
        echo "  sudo systemctl status lookout-s3-logger"
        echo "  sudo systemctl stop lookout-s3-logger"
        echo "  sudo systemctl restart lookout-s3-logger"
        echo "  journalctl -u lookout-s3-logger -f"
        
        exit 0
    fi
}

# Handle command line arguments
case "${1:-}" in
    --help|-h)
        echo "Lookout S3 Logger Setup Script"
        echo
        echo "Usage:"
        echo "  $0                    # Interactive setup"
        echo "  $0 --install-service  # Install systemd service (requires sudo)"
        echo "  $0 --help            # Show this help"
        exit 0
        ;;
    --install-service)
        check_systemd_install "$1"
        ;;
    *)
        main
        ;;
esac
